# Copyright 2020 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""
Yosys is a framework for RTL synthesis tools. It currently has extensive
Verilog-2005 support and provides a basic set of synthesis algorithms for
various application domains.
"""

load("@rules_cc//cc:defs.bzl", "cc_binary", "cc_library", "cc_test")
load("@rules_python//python:defs.bzl", "py_binary")
load("//bazel:yosys.bzl", "yosys_syntax_check", "move_files", "pm_rule")
load("//bazel:yacclex_helpers.bzl", "genyacc", "genlex")

licenses(["restricted"])

exports_files(["LICENSE"])

genrule(
    name = "version_src",
    outs = ["kernel/version.cc"],
    cmd = "echo 'namespace Yosys { " +
          "extern const char *yosys_version_str; " +
          "const char *yosys_version_str=\"Yosys 0.52+139\"; " +
          "}' >$@",
)

cc_library(
    name = "version",
    srcs = ["kernel/version.cc"],
    visibility = ["//visibility:public"],
)

genrule(
    name = "techmap",
    srcs = ["techlibs/common/techmap.v"],
    outs = ["techlibs/common/techmap.inc"],
    cmd = ("echo '// autogenerated from techmap.v' > $@ && " +
           "echo 'static char stdcells_code[] = {' >> $@ && " +
           "od -v -td1 -An $< | sed -e 's/[0-9][0-9]*/&,/g' >> $@ && " +
           "echo '0};' >> $@"),
)

genlex(
    name = "verilog_lexer",
    src = "frontends/verilog/verilog_lexer.l",
    out = "verilog_lexer.cc",
)

genyacc(
    name = "verilog_parser",
    src = "frontends/verilog/verilog_parser.y",
    header_out = "frontends/verilog/verilog_parser.tab.hh",
    source_out = "frontends/verilog/verilog_parser.tab.cc",
)

genlex(
    name = "rtlil_lexer",
    src = "frontends/rtlil/rtlil_lexer.l",
    out = "rtlil_lexer.cc",
)

genyacc(
    name = "rtlil_parser",
    src = "frontends/rtlil/rtlil_parser.y",
    header_out = "frontends/rtlil/rtlil_parser.tab.hh",
    source_out = "frontends/rtlil/rtlil_parser.tab.cc",
)

py_binary(
    name = "cellhelp",
    srcs = ["techlibs/common/cellhelp.py"],
    python_version = "PY3",
    srcs_version = "PY2AND3",
    deps = [
    ],
)

genrule(
    name = "simlib_help",
    srcs = [
        "techlibs/common/simlib.v",
    ],
    outs = ["techlibs/common/simlib_help.inc"],
    cmd = (
        "$(location :cellhelp) $(SRCS) > $@"
    ),
    tools = [":cellhelp"],
)

genrule(
    name = "simcells_help",
    srcs = [
        "techlibs/common/simcells.v",
    ],
    outs = ["techlibs/common/simcells_help.inc"],
    cmd = (
        "$(location :cellhelp) $(SRCS) > $@"
    ),
    tools = [":cellhelp"],
)

py_binary(
    name = "pmgen",
    srcs = ["passes/pmgen/pmgen.py"],
    python_version = "PY3",
    srcs_version = "PY3ONLY",
)

# Generate rules for every *.pmg we know about ---------------------
_PM_HDRS = [
    "techlibs/microchip/microchip_dsp_CREG_pm.h",
    "techlibs/microchip/microchip_dsp_pm.h",
    "techlibs/microchip/microchip_dsp_cascade_pm.h",
    "techlibs/xilinx/xilinx_dsp48a_pm.h",
    "techlibs/xilinx/xilinx_dsp_cascade_pm.h",
    "techlibs/xilinx/xilinx_srl_pm.h",
    "techlibs/xilinx/xilinx_dsp_CREG_pm.h",
    "techlibs/xilinx/xilinx_dsp_pm.h",
    "techlibs/ice40/ice40_wrapcarry_pm.h",
    "techlibs/ice40/ice40_dsp_pm.h",
    "techlibs/quicklogic/ql_dsp_macc_pm.h",
]

[pm_rule(_pmg.replace("/", "_").replace(".", "_") + "_pm_h", _pmg.replace("_pm.h", ".pmg"))
 for _pmg in _PM_HDRS]

genrule(
    name = "peepopt_pm_h",
    srcs = [
        "passes/opt/peepopt_shiftmul_left.pmg",
        "passes/opt/peepopt_muldiv.pmg",
        "passes/opt/peepopt_formal_clockgateff.pmg",
        "passes/opt/peepopt_shiftmul_right.pmg",
        "passes/opt/peepopt_shiftadd.pmg",
    ],
    outs = ["passes/opt/peepopt_pm.h"],
    cmd = "$(location :pmgen) -o $(OUTS) -p peepopt $(SRCS)",
    tools = [
        ":pmgen",
    ],
)

PM_H = _PM_HDRS + [
    "passes/opt/peepopt_pm.h",
]

YOSYS_COPTS = [
    "-fexceptions",
    "-Wno-implicit-fallthrough",
    "-Wno-maybe-uninitialized",
    "-Wno-misleading-indentation",
    "-Wno-unused-but-set-variable",
    "-Wno-unused-variable",
    "-Wno-unknown-warning-option",   # GCC vs Clang
    "-std=c++17",                    # new
    "-DYOSYS_SRC='\"./\"'",
]

cc_library(
    name = "kernel",
    srcs = glob(
        [
            "kernel/*.cc",
            "backends/**/*.cc",
            "frontends/**/*.cc",
            "passes/**/*.cc",
            "techlibs/**/*.cc",
        ],
        exclude = [
            "kernel/driver.cc",                          # binary only
            "backends/cxxrtl/runtime/**/*.cc",           # still optional
            "backends/protobuf/*.cc",                    # optional
            "passes/techmap/filterlib.cc",               # plugin
            "passes/pmgen/test_pmgen.cc",
        ],
    ) + [
        ":verilog_lexer",
        ":verilog_parser",
        ":rtlil_parser",
        ":rtlil_lexer",
        "techlibs/common/techmap.inc",
        "techlibs/common/simlib_help.inc",
        "techlibs/common/simcells_help.inc",
    ],
    hdrs = glob(
        [
            "kernel/*.h",
            "kernel/*.inc",
            "backends/**/*.h",
            "frontends/**/*.h",
            "passes/**/*.h",
            "techlibs/**/*.inc",

        ],
        exclude = [
            "backends/protobuf/*.h",
            "backends/cxxrtl/runtime/**/*.h",
        ],
    ) + PM_H,
    copts = YOSYS_COPTS,
    features = ["-use_header_modules"],
    includes = [
        "backends/ilang",
        "frontends/verilog",
        "frontends/rtlil",
        "passes/techmap",
        "techlibs/common",
    ],
    defines = [
        "_YOSYS_",
        "YOSYS_ENABLE_PLUGINS",
        "YOSYS_ENABLE_READLINE",
        "YOSYS_ENABLE_GLOB",
        "YOSYS_ENABLE_TCL",
        "YOSYS_ENABLE_ABC",
        "YOSYS_ENABLE_COVER",
        'ABCEXTERNAL=\\"abc\\"',
    ],
    deps = [
        ":bigint",
        ":ezsat",
        ":minisat",
        ":json11",
        ":sha1",
        ":subcircuit",
        ":fst",
        ":cxxopts",
        "@zlib//:zlib",                 # new – direct zlib refs
        "@readline//:readline",
        "@abc//:abc",
        "@libffi//:libffi",
        "@tcl//:tcl",
    ],
    alwayslink = True,
    visibility = ["//visibility:public"],
)

cc_binary(
    name = "yosys-bin",
    srcs = ["kernel/driver.cc"],
    copts = YOSYS_COPTS,
    features = ["-use_header_modules"],
    deps = [
        ":kernel",
        ":version",
        ":cxxopts",
        "@readline//:readline",
        "@zlib//:zlib",
    ],
    visibility = ["//visibility:public"],
)

# Wrapper that inserts required env vars such as
# YOSYS_DATDIR.
sh_binary(
    name = "yosys",
    srcs = ["yosys.sh"],
    data = [
        ":yosys-bin",
        ":share_files",
        "@abc//:abc_bin",
    ],
    deps = ["@bazel_tools//tools/bash/runfiles"],
    output_licenses = ["unencumbered"],
    visibility = ["//visibility:public"],
)

move_files(
  name = "common_techlibs",
  srcs = glob([
    "techlibs/common/*.v",
  ]),
  destination = "techlibs",
)

# So we can use the internal bzl dep without
# patching the repo.
# We are generating a double header to avoid recursive includes.
genrule(
    name = "_json11_stub_gen",
    outs = ["_json11_stub.hpp"],
    cmd = "\n".join([
        "cat <<'EOF' >$@\n",
        "#include \"json11.hpp\"",
        "EOF"
    ]),
)

cc_library(
    name = "json11_stub",
    hdrs = [
        "_json11_stub.hpp",
    ],
    deps = [
        "@json11",
    ],
)

genrule(
    name = "json11_header_gen",
    outs = ["libs/json11/json11.hpp"],
    cmd = "\n".join([
        "cat <<'EOF' >$@\n",
        "#include \"_json11_stub.hpp\"",
        "EOF"
    ]),
)

cc_library(
    name = "json11",
    hdrs = [
        "libs/json11/json11.hpp",
    ],
    deps = [
        ":json11_stub",
    ],
    includes = ["libs/json11"],
)

filegroup(
  name = "share_files",
  srcs = glob(
    include = [
      "techlibs/**/*.v",
      "techlibs/**/*.vh",
      "techlibs/**/*.lib",
      "techlibs/**/*.txt",
    ],
    exclude = [
        "techlibs/common/*.v",
    ]
  ) + [
    ":common_techlibs"
  ],
)

# So we can use the internal bzl dep without
# patching the repo.
# We are generating a double header to avoid recursive includes.
genrule(
    name = "_cxxopts_stub_gen",
    outs = ["_cxxopts_stub.hpp"],
    cmd = "\n".join([
        "cat <<'EOF' >$@\n",
        "#include \"cxxopts.hpp\"",
        "EOF"
    ]),
)

cc_library(
    name = "cxxopts_stub",
    hdrs = [
        "_cxxopts_stub.hpp",
    ],
    deps = [
        "@cxxopts",
    ],
)

genrule(
    name = "cxxopts_header_gen",
    outs = ["libs/cxxopts/include/cxxopts.hpp"],
    cmd = "\n".join([
        "cat <<'EOF' >$@\n",
        "#include \"_cxxopts_stub.hpp\"",
        "EOF"
    ]),
)

cc_library(
    name = "cxxopts",
    hdrs = [
        "libs/cxxopts/include/cxxopts.hpp",
    ],
    includes = ["libs/cxxopts/include"],
    deps = [
        ":cxxopts_stub",
    ]
)

cc_library(
    name = "fst",
    srcs = [
        "libs/fst/fastlz.cc",
        "libs/fst/fstapi.cc",
        "libs/fst/lz4.cc",
    ],
    hdrs = [
        "libs/fst/config.h",
        "libs/fst/fastlz.h",
        "libs/fst/fstapi.h",
        "libs/fst/lz4.h",
    ],
    deps = [
        "@zlib//:zlib",
    ],
    licenses = ["notice"],
)


cc_library(
    name = "minisat",
    srcs = [
        "libs/minisat/Options.cc",
        "libs/minisat/SimpSolver.cc",
        "libs/minisat/Solver.cc",
        "libs/minisat/System.cc",
    ],
    hdrs = [
        "libs/minisat/ParseUtils.h",
        "libs/minisat/Heap.h",
        "libs/minisat/Queue.h",
        "libs/minisat/IntMap.h",
        "libs/minisat/SolverTypes.h",
        "libs/minisat/IntTypes.h",
        "libs/minisat/SimpSolver.h",
        "libs/minisat/System.h",
        "libs/minisat/Sort.h",
        "libs/minisat/Map.h",
        "libs/minisat/Vec.h",
        "libs/minisat/Options.h",
        "libs/minisat/XAlloc.h",
        "libs/minisat/Alloc.h",
        "libs/minisat/Solver.h",
        "libs/minisat/Rnd.h",
        "libs/minisat/Alg.h",
        "libs/minisat/Dimacs.h",
    ],
    copts = [
        "-fexceptions",
    ],
    features = ["-use_header_modules"],
    licenses = ["notice"],
)

cc_library(
    name = "ezsat",
    srcs = [
        "libs/ezsat/ezminisat.cc",
        "libs/ezsat/ezsat.cc",
    ],
    hdrs = [
        "libs/ezsat/ezminisat.h",
        "libs/ezsat/ezsat.h",
    ],
    copts = [
        "-fexceptions",
    ],
    features = ["-use_header_modules"],
    deps = [
        ":minisat",
    ],
    licenses = ["notice"],
)

cc_test(
    name = "ezsat_demo_vec",
    srcs = [
        "libs/ezsat/demo_vec.cc",
    ],
    deps = [":ezsat"],
    licenses = ["notice"],
)

cc_test(
    name = "ezsat_demo_bit",
    srcs = [
        "libs/ezsat/demo_bit.cc",
    ],
    deps = [":ezsat"],
    licenses = ["notice"],
)

cc_test(
    name = "ezsat_demo_cmp",
    srcs = [
        "libs/ezsat/demo_cmp.cc",
    ],
    deps = [":ezsat"],
    licenses = ["notice"],
)

cc_test(
    name = "ezsat_puzzle3d",
    timeout = "eternal",
    srcs = [
        "libs/ezsat/puzzle3d.cc",
    ],
    deps = [":ezsat"],
    licenses = ["notice"],
)

cc_library(
    name = "sha1",
    srcs = [
        "libs/sha1/sha1.cpp",
    ],
    hdrs = ["libs/sha1/sha1.h"],
    licenses = ["notice"],
)


cc_library(
    name = "bigint",
    srcs = [
        "libs/bigint/BigInteger.cc",
        "libs/bigint/BigIntegerAlgorithms.cc",
        "libs/bigint/BigIntegerUtils.cc",
        "libs/bigint/BigUnsigned.cc",
        "libs/bigint/BigUnsignedInABase.cc",
    ],
    hdrs = [
        "libs/bigint/BigInteger.hh",
        "libs/bigint/BigIntegerAlgorithms.hh",
        "libs/bigint/BigIntegerLibrary.hh",
        "libs/bigint/BigIntegerUtils.hh",
        "libs/bigint/BigUnsigned.hh",
        "libs/bigint/BigUnsignedInABase.hh",
        "libs/bigint/NumberlikeArray.hh",
    ],
    copts = [
        "-fexceptions",
    ],
    features = ["-use_header_modules"],
    licenses = ["notice"],
)

yosys_syntax_check(
    name = "testing_yosys_syntax_check_build_rule",
    srcs = [
        "examples/cmos/cmos_cells.v",
        "examples/cmos/counter.v",
    ],
)

cc_test(
    name = "bigint_sample",
    srcs = [
        "libs/bigint/sample.cc",
    ],
    copts = [
        "-fexceptions",
    ],
    features = ["-use_header_modules"],
    deps = [":bigint"],
    licenses = ["notice"],
)

cc_binary(
    name = "subcircuit_shell",
    srcs = [
        "libs/subcircuit/scshell.cc",
    ],
    deps = [":subcircuit"],
    licenses = ["notice"],
)

cc_library(
    name = "subcircuit",
    srcs = [
        "libs/subcircuit/subcircuit.cc",
    ],
    hdrs = ["libs/subcircuit/subcircuit.h"],
    licenses = ["notice"],
)
