module(
    name = "yosys",
    version = "0.52.0"
)

bazel_dep(name = "rules_flex", version = "0.4")
bazel_dep(name = "rules_bison", version = "0.4")
bazel_dep(name = "sed", version = "4.9.bcr.1")
bazel_dep(name = "rules_m4", version = "0.3")
bazel_dep(name = "readline", version = "8.2.bcr.1")
bazel_dep(name = "zlib", version = "1.3.1.bcr.5")
bazel_dep(name = "rules_cc", version = "0.1.1")
bazel_dep(name = "bazel_skylib", version = "1.7.1")
bazel_dep(name = "rules_python", version = "1.4.0")
bazel_dep(name = "abc", version = "0.0.0-20250408-yosyshq.bcr.1")
bazel_dep(name = "libffi", version = "3.4.7.bcr.3")
bazel_dep(name = "tcl", version = "8.6.10")
bazel_dep(name = "json11", version = "1.0.1-0.20200325232727-2df9473fb360")

git_override(
    module_name = "tcl",
    commit = "4ca5c6850eae1a24b611a76a68eff0b31c840823",
    remote = "https://github.com/amorphic-io/tcl.git",
)
git_override(
    module_name = "abc",
    commit = "2fa8f6e551a85da586fbe01792e6cfdaa7ce72cc",
    remote = "https://github.com/amorphic-io/abc",
)
git_override(
    module_name = "ncurses",
    commit = "f918fafc9f7aeb1745d02e7978597abf8e580de2",
    remote = "https://github.com/amorphic-io/ncurses",
)

python = use_extension("@rules_python//python/extensions:python.bzl", "python")
python.toolchain(
    python_version = "3.13",
)
